### PR TITLE
Added contributors section at the bottom

### PR DESCRIPTION
**Pull request by Pricetx**
Added a contributors section to the bottom of the census page with a list of the key contributors and some relevant links.

See the following URL to see an example: https://s3.eu-west-2.amazonaws.com/dev.ffxivcensus.com/test3.html

### CODE REVIEW

**Comment by ReidWeb** [comment]
Probs best to get approval from all those affected!

**Comment by ReidWeb** [comment]
lol too late

**Comment by fahy** [comment]
[Approved (??) 👍](https://media1.tenor.com/images/1877d742a3f57461ec12c7d51d10cd65/tenor.gif)

**Comment by matthewhillier** [comment]
🤣 👍

**Pull request merged**
