### PR TITLE
Gear & UX Update

### PR DESCRIPTION
**Pull request by matthewhillier**
A (turned out to be) quite extensive update to the PHP page.

This started off as the additions for the Gear Gathering update to the Java gatherer, but may have gotten a little carried away... :)

Changed in this branch:
- Added Gear stats (needs a DB generated by the gear_gathering branch of the Java project)
- Reworked the sections of the census to group them together based on the type of data / narrative
- Tidied up some of the graph displays
- Added Eureka stats

### CODE REVIEW

**Comment by matthewhillier** [comment]
Preview here: [xivstats.zip](https://github.com/XIVStats/XIVStats/files/3376653/xivstats.zip) (Sorry, didn't have anywhere to publish this).

**Comment by crakila** [comment]
Live Preview: https://crakila.dev/xiv/49/

**Comment by crakila** [comment]
Gonna wait for https://github.com/XIVStats/XIVStats-Gatherer-Java/pull/53 to be approved and then grab a new DB and test.

**Comment by matthewhillier** [comment]
There's a compatriot branch in the Gatherer that added additional tables to the DB, but that's equally out of date. We can probably close this and decide if we're interested in gear at all - it'll need to be reimplemented either way.

There were a few ideas on how to layout the site page, which might be worth revisiting? 🤷‍♂️

**Comment by crakila** [comment]
I'll close this for now. We can reference this PR in the future when the new gatherer is near completion and we are ready to create the newer web page.

**Pull request closed without merging**
