### PR TITLE
Add new Shadow World, Tycoon

### PR DESCRIPTION
**Pull request by Crakila**
This is a follow-up to #91 
This adds a 4th world to the new Shadow DC.

* Added Tycoon

Source: https://eu.finalfantasyxiv.com/lodestone/topics/detail/31684d7bc88f06d5a8ffc43968a6eaae4b706d00

### CODE REVIEW

**Review by ReidWeb — APPROVED** [review]

**Comment by ReidWeb** [comment]
Hmm, are these worlds actually going to allow for character creation?

**Comment by Crakila** [comment]
No idea. They say that players will be able to migrate to it for the purpose of the Dawntrail expansion launch. I would like to assume they are keeping them...

**Comment by ReidWeb** [comment]
> These Worlds will be released as probationary Worlds to mitigate the congestion that may arise with Dawntrail's launch and will only be available for the purposes of Data Center Travel.
> 
>  Probationary Worlds will be restricted from new character creation and the Home World Transfer Service

Characters won't exist on them, source being the article you linked

**Comment by Crakila** [comment]
I would like to assume that even SE are going to be monitoring the Dawntrail launch and seeing if it warrants them keeping the servers and allowing character creation.

I propose that we keep the server names added until the release of 7.1 unless SE makes a statement about it between now and then, stating otherwise.

**Comment by Crakila** [comment]
That's cool. I'll remove them for now. And sure it can be re-added handy enough. 
#94

**Pull request merged**
