### PR TITLE
January 2022 Update 

### PR DESCRIPTION
**Pull request by crakila**
This includes some long-standing items that were missing:

* Items missing from Heavensward (Such as Beast Tribes, OST's, Art Books, etc) have been added.
* Plushes have been added.
* Missing OST's have been added.
* Missing Art Books have been added.
* 500 Commendations and 3000 Commendation have been added.
* Hildibrand Questlines 

* Checks for the Collectors Editions have changed.
    * Square-Enix has merged the platform specific collectors editions for ARR to be just part of the overall Collectors Edition. This has been updated to only show as "ARR Collectors Edition". 
    * Heavensward has been added.

* Added Ocenaia Data Center

* Support for the FFXIV Lodestone has been implemented.
    * Hover over any item in the 'Pre-order' section to see the item that is required.
    * [Obviously, the item for the 6.0 MSQ check is not included]

* Multiple items required for a check has been implemented.

    * Example: 
    * Before we were just checking for the "Wind-up Kobold" minion for the ARR Kobold Beast Tribe check.
    * Now we can check for either the minion OR the "Bomb Palanquin" mount. 
    * [This has been added for all Beast Tribes except for the Ixal Beast Tribes.]

* A button going to our statement on GitHub ( https://github.com/XIVStats/XIVStats/issues/57 ) has been added. 

The update can be previewed on https://crakila.dev/xiv/ (With little to no actual data :P ) 

TODO:

* Fix anchors

### CODE REVIEW

**Comment by ReidWeb** [comment]
Will review later

**Review by ReidWeb — APPROVED** [review]
Looks terrific Padraig, great work.

@Pricetx - not sure how to pull this in for a run in the dev env? Is it a similar protocol to doing it for the gatherer? Would maybe want to get a run through? I can give it a spin or you can?

**Comment by matthewhillier** [comment]
This looks awesome @crakila!

Just one observation - the menu hover color seems to make the text harder to read:
image

Perhaps keep it white, or emboledn it a little so that there's enough contrast?

**Comment by crakila** [comment]
Thanks @matthewhillier 

Yeah, the nav bar/menu needs some love and I plan to fix the styling of that along with the anchors. :)

**Pull request merged**
